version: '3.7'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - 8000

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - backend